---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: my-secret
    creationPolicy: Owner
  data:
    - secretKey: name
      remoteRef:
        key: secret-demo
        property: name
    - secretKey: password
      remoteRef:
        key: secret-demo
        property: password
